In [1]:
!pip install scikit-learn

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
Weight = np.array([2,4,5,3,6,5,7])
Price  = np.array([35,60,20,50,50,55,60])

df= pd.DataFrame({'Weight': Weight, 'Price': Price})
df

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

## Manual calculation using formula 
#### Task 1

In [5]:
x = df['Weight']
y = df['Price']
print(x)
print(y)

0    2
1    4
2    5
3    3
4    6
5    5
6    7
Name: Weight, dtype: int32
0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: Price, dtype: int32


In [6]:
mean_x = np.mean(x)
mean_y = np.mean(y)

slope = np.sum((x - mean_x)*(y - mean_y))/np.sum((x-mean_x)**2)
print(slope)

2.620967741935484


In [7]:
intercept = mean_y - slope*mean_x
intercept

35.16129032258065

In [8]:
price_predict = 35.16129 + 2.621*6  #predicting the price when the vegetable weight is 6
price_predict

50.88729

### Task 02

### Compute the residuals  for each data point 

In [9]:
Weight = np.array([2,4,5,3,6,5,7])
Price  = np.array([35,60,20,50,50,55,60])

df= pd.DataFrame({'Weight': Weight, 'Price': Price})
df

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [10]:
model  = LinearRegression().fit(df[['Weight']],df[['Price']])

slope_sklearn = model.coef_
slope_sklearn

array([[2.62096774]])

In [11]:
Intercept_sklearn = model.intercept_
Intercept_sklearn

array([35.16129032])

In [12]:
df['Pred_y']= model.predict(df[['Weight']])
df

Weight  Price     Pred_y
0       2     35  40.403226
1       4     60  45.645161
2       5     20  48.266129
3       3     50  43.024194
4       6     50  50.887097
5       5     55  48.266129
6       7     60  53.508065

In [13]:
df['Residuals'] = df['Price'] - df['Pred_y']
df

Weight  Price     Pred_y  Residuals
0       2     35  40.403226  -5.403226
1       4     60  45.645161  14.354839
2       5     20  48.266129 -28.266129
3       3     50  43.024194   6.975806
4       6     50  50.887097  -0.887097
5       5     55  48.266129   6.733871
6       7     60  53.508065   6.491935

### Task 03
#### Calculate both the Mean Squared Error and Mean Absolute Error

In [14]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [15]:
mse = mean_squared_error(df['Price'], df['Pred_y'])
mse

167.30990783410135

In [16]:
mae = mean_absolute_error(df['Price'], df['Pred_y'])
mae

9.87327188940092

### Final Task 
#### Generate an excel file for the  given dataset , Utilize Python for all calculation.

In [17]:
data = pd.read_excel("E:/SDC/DS & ML Course Modeuls/AiQuest Datas/Class 4/Assignment-04.xlsx")
data

Weight_01  Price_01
0          2        35
1          4        60
2          5        20
3          3        50
4          6        50
5          5        55
6          7        60

In [18]:
np.array(data)

array([[ 2, 35],
       [ 4, 60],
       [ 5, 20],
       [ 3, 50],
       [ 6, 50],
       [ 5, 55],
       [ 7, 60]], dtype=int64)

In [20]:
model_fit = LinearRegression().fit(data[["Weight_01"]], data[["Price_01"]])



In [21]:
slp_sklearn = model_fit.coef_
slp_sklearn


array([[2.62096774]])

In [22]:
intercept_sklearnC =model.intercept_
intercept_sklearnC

array([35.16129032])

#### Predicting

In [24]:
data[["Pred_Price"]] = model_fit.predict(data[["Weight_01"]])
data

Weight_01  Price_01  Pred_Price
0          2        35   40.403226
1          4        60   45.645161
2          5        20   48.266129
3          3        50   43.024194
4          6        50   50.887097
5          5        55   48.266129
6          7        60   53.508065

#### Calculating Residuals 

In [29]:
data["Residuals"] = data["Price_01"] - data["Pred_Price"]
data

Weight_01  Price_01  Pred_Price  Residuals
0          2        35   40.403226  -5.403226
1          4        60   45.645161  14.354839
2          5        20   48.266129 -28.266129
3          3        50   43.024194   6.975806
4          6        50   50.887097  -0.887097
5          5        55   48.266129   6.733871
6          7        60   53.508065   6.491935

#### Calculating MSE, MAE, RMSE

In [32]:
mse_01 = mean_squared_error(data["Price_01"], data["Pred_Price"])
mse_01

167.30990783410135

In [33]:
mae_01 = mean_absolute_error(data["Price_01"], data["Pred_Price"])
mae_01

9.87327188940092

In [35]:
import math 
math.sqrt(mse_01)

12.934833119685052